"""empty message

Revision ID: 070ba0acf868
Revises: b72940b7a4a4
Create Date: 2022-05-20 15:47:52.709133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '070ba0acf868'
down_revision = 'b72940b7a4a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('poster_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'users', ['poster_id'], ['id'])
    op.drop_column('posts', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author', sa.VARCHAR(length=128), nullable=False))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'poster_id')
    # ### end Alembic commands ###
