"""empty message

Revision ID: d48b67fc6aa5
Revises: 8543f94f68ca
Create Date: 2022-05-20 09:04:00.720772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd48b67fc6aa5'
down_revision = '8543f94f68ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=256), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=256), nullable=True))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
